INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 11, '대답1', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 10, '대답2', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 9, '대답3', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 8, '대답4', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 7, '대답5', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 6, '대답6', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 5, '대답7', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 4, '대답8', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 3, '대답9', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 2, '대답10', SYSDATE);
INSERT INTO INQUIRY
VALUES (INQUIRY_SEQ.NEXTVAL, 1, '대답11', SYSDATE);