INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 1, '질문1', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 2, '질문2', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 3, '질문3', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 3, '질문4', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 4, '질문5', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 4, '질문6', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 6, '질문7', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 6, '질문8', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 4, '질문9', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 6, '질문10', SYSDATE, '카테고리 선택!!');
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 1, '질문11', SYSDATE, '카테고리 선택!!');