INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 1, '질문1', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 2, '질문2', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 3, '질문3', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 3, '질문4', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 4, '질문5', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 4, '질문6', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 6, '질문7', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 6, '질문8', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 4, '질문9', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 6, '질문10', SYSDATE);
INSERT INTO QA
VALUES (QA_SEQ.NEXTVAL, 1, '질문11', SYSDATE);